USE gold;

-- 1) Find the date of the first and last order and find how many years of sales are available.
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
    TIMESTAMPDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM fact_sales;

-- 2) Find the youngest and oldest customer
SELECT 
    MIN(birthdate) AS oldest_birthdate,
    TIMESTAMPDIFF(YEAR, MIN(birthdate), CURDATE()) AS oldest_age,
    MAX(birthdate) AS youngest_birthdate,
    TIMESTAMPDIFF(YEAR, MAX(birthdate), CURDATE()) AS youngest_age
FROM dim_customers;

-- 3) Find the total sales
SELECT 
	SUM(sales_amount) AS total_sales 
FROM fact_sales;

-- 4) Find how many items are sold
SELECT 
	SUM(quantity) AS total_quantity 
FROM fact_sales;

-- 5) Find the average selling price
SELECT 
	AVG(price) AS avg_price 
FROM fact_sales;

-- 6) Find the total number of orders
SELECT 
	COUNT(order_number) AS total_orders
FROM fact_sales;

-- Use DISTINCT to avoid duplicates (1 order per customer because there could be a customer that ordered multiple products)
SELECT 
	COUNT(DISTINCT order_number) AS total_orders
FROM fact_sales;

-- 7) Find the total number of products.
SELECT 
	COUNT(product_name) AS total_products 
FROM dim_products;

-- Use DISTINCT to avoid duplicates
SELECT 
	COUNT(DISTINCT product_name) AS total_products 
FROM dim_products;

-- 8) Find the total number of customers.
SELECT 
	COUNT(customer_key) AS total_customers
FROM fact_sales;

-- 9) Find the total number of customers that has placed an order
SELECT 
	COUNT(DISTINCT customer_key) AS total_customers
FROM fact_sales;

-- 10) Generate a report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity) FROM fact_sales
UNION ALL
SELECT 'Average Price', AVG(price) FROM fact_sales
UNION ALL
SELECT 'Total Nr. Orders', COUNT(DISTINCT order_number) FROM fact_sales
UNION ALL
SELECT 'Total Nr. Products', COUNT(product_name) FROM dim_products
UNION ALL
SELECT 'Total Nr. Customers', COUNT(customer_key) FROM dim_customers;

-- 11) Find total customers by countries.
SELECT 
	country,
    COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY country
ORDER BY total_customers DESC
;

-- 12) Find total customers by gender.
SELECT 
	gender,
    COUNT(customer_key) AS total_customers
FROM dim_customers
GROUP BY gender
ORDER BY total_customers DESC
;

-- 13) Find total products by category.
SELECT 
	category,
	COUNT(product_key) AS total_products
FROM dim_products
GROUP BY category
ORDER BY total_products DESC
;

-- 14) What is the average costs in each category?
SELECT 
	category,
	AVG(cost) AS avg_costs
FROM dim_products
GROUP BY category
ORDER BY avg_costs DESC
;

-- 15) What is the total revenue generated for each category?
SELECT 
	p.category,
    SUM(f.sales_amount) total_revenue
FROM fact_sales AS f
		LEFT JOIN dim_products AS p
	ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC
; 

-- 16) Find the total revenue generated by each customer.
SELECT 
	c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales AS f
		LEFT JOIN dim_customers AS c
	ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC
;

-- 17) What is the distribution of sold items across countries?
SELECT 
	c.country,
    SUM(f.quantity) AS total_sold_items
FROM fact_sales AS f
		LEFT JOIN dim_customers AS c
	ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
;

-- 18) Which 5 products generate the highest revenue?
SELECT 
	p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales AS f
		LEFT JOIN dim_products AS p
	ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5
;

-- 19) What are the 5 worst performing products in terms of sales?
SELECT 
	p.product_name,
    SUM(f.sales_amount) AS total_revenue
FROM fact_sales AS f
		LEFT JOIN dim_products AS p
	ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue DESC
LIMIT 5
;

-- 20) Find the top 10 customers who have generated the highest revenue. 
SELECT
	c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM fact_sales AS f
		LEFT JOIN dim_customers AS c
	ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC
LIMIT 10
;

-- 21) Find the 3 customers with the fewest orders placed
SELECT
	c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM fact_sales AS f
		LEFT JOIN dim_customers AS c
	ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_orders DESC
LIMIT 3
;